### ISSUE TITLE
ImportError on  load_neuropod

### ISSUE THREAD

**Issue by w4nderlust** [uber/neuropod#387] opened 2020-06-10 00:47 UTC
## Bug

Get `ImportError` when loading a neuropod:
`ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory`

## To Reproduce

```
>>> from neuropod.loader import load_neuropod
>>> load_neuropod("neuropod_path")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/loader.py", line 211, in load_neuropod
    return NativeNeuropodExecutor(neuropod_path, **kwargs)
  File "/home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/loader.py", line 114, in __init__
    from neuropod.neuropod_native import Neuropod as NeuropodNative
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

This happens on this line in the neuropod test inside Ludwig:
https://github.com/uber/ludwig/blob/master/tests/integration_tests/test_neuropod.py#L118

You can use that whole code to reproduce the issue.
Note that that same code was working fine with version 0.1.x of neuropod (the internal version).

## Expected behavior

The model gets loaded.

## Environment

 - Neuropod Version: 0.2.0
 - OS: Ubuntu Linux 20.04
 - Language (Python, C++, Go bindings): Python
 - Python version: Python 3.7.7

**Comment by VivekPanyam** [comment] 2020-06-10 01:10
From the trace you posted above, it looks like the line that's failing is
```
from neuropod.neuropod_native import Neuropod as NeuropodNative
```

In a Python 3.7 Docker container, that line seems to work:
```
docker run -it --rm  python:3.7 /bin/bash
root@e57aec219521:/# pip install neuropod
[snip]
root@e57aec219521:/# python
Python 3.7.7 (default, Mar 31 2020, 15:46:29)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from neuropod.neuropod_native import Neuropod as NeuropodNative
>>>
```

I just cloned the Ludwig repo and tried to run `test_neuropod.py` in a Python 3.7 container and the test passed.

What's the output of the following command on your machine?

```
ldd /home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/neuropod_native.so
```

**Comment by w4nderlust** [comment] 2020-06-10 01:14
Here it is:
```
> ldd /home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/neuropod_native.so
	linux-vdso.so.1 (0x00007fff7234d000)
	libneuropod.so => /home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/libneuropod.so (0x00007f542bd5e000)
	libpython3.7m.so.1.0 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f542bbe8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f542ba07000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f542b9ec000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f542b9c7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f542b9c1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f542b7cf000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f542c1db000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f542b7c4000)
```

Also confirming I'm not developing from within a docker, but just using a virtualenv on my machine.

**Comment by VivekPanyam** [comment] 2020-06-10 01:22
Hmm does `/usr/local/lib/libpython3.7m.so.1.0` exist?

(if not, what's the output of `find / -name libpython3.7m.so.1.0`)

**Comment by w4nderlust** [comment] 2020-06-10 01:26
Ubuntu 20.04 ships with python 3.8, so this python 3.7 I installed myself compiling from source and then running `make install`, so it may be placing and naming files in a slighlty diferent way than regular.

Anyway
`/usr/local/lib/libpython3.7m.so.1.0`
does not exist, but I got this:
```
> ls -l /usr/local/lib/ | grep libpython
-r-xr-xr-x  1 root root   35735730 Apr 25 11:26 libpython3.7m.a
``

**Comment by vkuzmin-uber** [comment] 2020-06-10 01:47
I think I observer similiar problen when installed neuropod from rleases:

```
importError: dlopen(/Users/vkuzmin/workspaces/tests/venv/lib/python3.7/site-packages/neuropod/neuropod_native.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.7/Python
  Referenced from: /Users/vkuzmin/workspaces/tests/venv/lib/python3.7/site-packages/neuropod/neuropod_native.so
  Reason: image not found
```

But I don't have path at /Library/Frameworks/Python.framework/Versions/3.7/Python

ls /Library/Frameworks/Python.framework/Versions/3.7/Python
ls: /Library/Frameworks/Python.framework/Versions/3.7/Python: No such file or directory

It seems that neuropod_native.so expects exactly the same paths in a build and runtime environment?

**Comment by tomzhang** [comment] 2020-06-16 06:25
I recommend that people can using conda to manage multi-version of python env that will resolve all this kind of problems without any pain.
there is the full explanation of the solution:
[multi-version python management with conda](https://stackoverflow.com/questions/46998581/changing-conda-default-python-version)

**Comment by w4nderlust** [comment] 2020-06-16 08:17
Not really sure why conda would solve the issue, can you elaborate please?
Also I'm not sure neuropod as a project wants to have a dependency on conda to work, there should be a way to make it work with regular virtualenv aswell imho.

**Comment by VivekPanyam** [comment] 2020-06-16 17:54
> I think I observed similar problem when installed neuropod from releases at my OSX

Library loading on Linux and macOS are fairly different unfortunately. The PR I just put up (#389) should fix the import issue on both platforms, but we'll still run into similar issues when attempting to run a Python/PyTorch model.

This is because loading a Python/PyTorch neuropod will cause `libneuropod_pythonbridge_backend.so` to be loaded (which depends on libpython) and we get back to the same issue.

I'm working on making the python backend fully self-contained (as the other ones are), but doing so with Python is a little trickier. Hopefully I'll have a PR ready soon.

**Comment by w4nderlust** [comment] 2020-06-16 19:40
Thanks @VivekPanyam , let me know when you want me to test it out!

**Comment by sepo-eng** [comment] 2020-06-16 23:31
@VivekPanyam, not sure if it's helpful, but I was able to work around the issue Vlad mentioned with his help by updating the python dependency on neuropod_native.so.

> install_name_tool -change /Library/Frameworks/Python.framework/Versions/3.7/Python /usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/Python neuropod_native.so

Is there a similar command to install_name_tool in Linux like patchelf that may be a possible workaround?

**Comment by w4nderlust** [comment] 2020-06-16 23:55
Have never used it, but maybe this could be useful: https://github.com/NixOS/patchelf

**Comment by VivekPanyam** [comment] 2020-06-17 00:01
I was going to mention a workaround with patchelf to remove the dependency on `libpython3.7m.so.1.0`, but then you'd likely hit the second issue I referenced in my comment above so it wouldn't really get you anywhere.

If you want a workaround in the meantime, you can try installing `libpython3.7-dev`:

```
# Add a repo that contains several python builds
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt-get update

# Install libpython
sudo apt-get install libpython3.7-dev
```

**Comment by w4nderlust** [comment] 2020-06-17 00:29
Thank @VivekPanyam , with this the test passes!
Will still wait for a fully fledged solution, as i feel that this open up a more general can of worms to be figured out :)

**Comment by vkuzmin-uber** [comment] 2020-06-17 04:07
> Ubuntu 20.04 ships with python 3.8, so this python 3.7 I installed myself compiling from source and then running `make install`, so it may be placing and naming files in a slighlty diferent way than regular.
> 
> Anyway
> `/usr/local/lib/libpython3.7m.so.1.0`
> does not exist, but I got this:
> 
> ```
> > ls -l /usr/local/lib/ | grep libpython
> -r-xr-xr-x  1 root root   35735730 Apr 25 11:26 libpython3.7m.a
> ``
> ```

I know what happened namely in your case here. You built Python from sources, I guess with

./configure --enable-optimizations

it creates "fat" Python binary w/o shared library. Neuropod uses libpython and this is why it expects that Python is built as:

./configure --enable-optimizations --enable-shared
make -j 2
make install (or make altinstall)

You can also specify here where library should go with --prefix, or by default it will be in /usr/local/lib.

At Debian /usr/local/lib is not a "standard" directory (not sure about Ubuntu). If you run "python3.7 --version, it will try to load libpython*so) and you either should  append it to LD_LIBRARY_PATH or

```
    # Library is installed to /usr/local/lib that is not default path at Debian
    # make it available globally.
    ls -l /etc/ld.so.conf.d/
    echo "/usr/local/lib" > /etc/ld.so.conf.d/python.conf
    ldconfig -v
```

So, in your case the problem is because of the way you built Python.

**Comment by w4nderlust** [comment] 2020-06-17 04:15
Thanks @vkuzmin-uber . Will try rebuilding it. Will confirm if this solves the issue.

**Comment by w4nderlust** [comment] 2020-06-17 23:38
So I recompiled python 3.7 with --enable-shared, reinstalled (make altinstall),, modified python.conf,  and created a new virtualenv.

```
ldd /home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/neuropod_native.so
	linux-vdso.so.1 (0x00007ffd286e1000)
	libneuropod.so => /home/piero/dev/mlvenv/lib/python3.7/site-packages/neuropod/libneuropod.so (0x00007f9a8bdae000)
	libpython3.7m.so.1.0 => /usr/local/lib/libpython3.7m.so.1.0 (0x00007f9a8ba1d000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9a8b8ce000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f9a8b6ed000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9a8b6d2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f9a8b6ad000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f9a8b6a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9a8b4b5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9a8c22b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f9a8b4aa000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f9a8b4a5000)
```

Now i don-t get the error with libpython3, but I get a different one:
```
self = <neuropod.loader.NativeNeuropodExecutor object at 0x7f2ee9077390>
neuropod_path = 'neuropod', kwargs = {}
NeuropodNative = <class 'neuropod.neuropod_native.Neuropod'>

    def __init__(self, neuropod_path, **kwargs):
        """
        Load a Neuropod using the native bindings
    
        :param  neuropod_path:  The path to a neuropod package
        """
        # Load the model
        from neuropod.neuropod_native import Neuropod as NeuropodNative
    
        self.model = NeuropodNative(
>           neuropod_path, _REGISTERED_BACKENDS, use_ope=True, **kwargs
        )
E       RuntimeError: Neuropod Error: Got an exception when loading the model at neuropod: Neuropod Error: Loading the default backend for type 'python' failed. Error from dlopen: libneuropod_pythonbridge_backend.so: cannot open shared object file: No such file or directory

../../../mlvenv/lib/python3.7/site-packages/neuropod/loader.py:117: RuntimeError
```

Not sure it's worth debugging, as it is something probably specific to my configuration, but maybe if this is revealing of something Neuropod should take into account moving forward, help to keep debugging for figuring this out, your call.

**Comment by vkuzmin-uber** [comment] 2020-06-18 02:45
I guess you need to install Python backend. Neuropod 0.2.0 has separate
packages now for core and every backend. Look doc or just check releases
page.

**Comment by w4nderlust** [comment] 2020-06-18 03:32
Great, after installing the backend, it passes the test!
So a minor suggestion, maybe that arreor can be cought and instructions for downloading the backend can be given. Also, depending on the function called and on the version of python/tf/pytorch imported (which are easy to figure out( the right backend could be downloaded automatically, or an error saying the current combination is not supported can be shown.

**Comment by VivekPanyam** [comment] 2020-06-18 04:05
Yeah, that makes sense. The intended error message is much more clear:
https://github.com/uber/neuropod/blob/4f5764af8f29d1ca241f9576cf4ea5bae5c025dd/source/neuropod/internal/backend_registration.cc#L248-L253

but unfortunately, it seems like another error is thrown first.

See https://github.com/uber/neuropod/issues/383#issuecomment-641480620 for more details

**Comment by vkuzmin-uber** [comment] 2020-06-18 05:41
@VivekPanyam while we are in the context. I found that many people can be confused when building Python for neuropod, it is not obvious that it needs to be done with "enable-shared" 

```
./configure --enable-optimizations --enable-shared
```

"official" python packages are fine, the problem when somebody decided to build Python from sources.

Do you think we can document somehow that neuropod needs "embedded" Python and so, if building from sources, it should be enabled.

**Closed** 2020-06-18 21:07 UTC

**Comment by w4nderlust** [comment] 2020-06-18 21:23
Thank you for your help guys!
