### ISSUE TITLE
SavedModel Load Issue 

### ISSUE THREAD

**Issue by voe09** [uber/neuropod#549] opened 2022-06-02 23:58 UTC
In neuropod tensorflow packager, if it is saved model format, it would do the following validation
```
        actual_outputs = set(
            name for name in loaded.signatures["serving_default"].structured_outputs
        )
        expected_outputs = set(tensor["name"] for tensor in output_spec)
        missing_outputs = expected_outputs - actual_outputs
```
The logics assume that the output tensor name is consistent with the feature name in output spec. The assumption is not correct. In Neuropod tensorflow backend, we actually map the tensor and the feature name based on the order.

**Comment by VivekPanyam** [comment] 2022-06-03 01:00
> The logics assume that the output tensor name is consistent with the feature name in output spec. The assumption is not correct.

The output tensor names must be consistent with the feature name in output spec. This is how Neuropod knows which tensor is which. This is a correct assumption because it's a requirement.

>   In Neuropod tensorflow backend, we actually map the tensor and the feature name based on the order.

When you say "based on the order", I assume you mean the order of things in the output spec. Please clarify if this isn't the ordering you're referring to.

The Neuropod TF backend does not depend on the order of items in the input/output spec.

As we've spoken about offline, we avoid depending on the order of items in the input/output spec because that introduces a brittle dependency on the order of items in the spec (same reason for not allowing return of a `List[Tensor]` or `Tuple[Tensor]` from TorchScript models). This can easily break, especially if there are several models using a centralized spec.


From what I can tell, the check you referenced in the issue is valid and necessary and we don't depend on the spec ordering in the TF backend. Feel free to comment if you were actually referring to something else.


I walked through some of the relevant parts of the code below and it should help clarify how inference with saved models works.

----

Here's a quick walkthrough of the relevant parts of the code:

1. The saved model is loaded and we set up a node name mapping that maps from the name of a Neuropod output to the corresponding node in the TF graph. For SavedModels, this is based on the signature of the saved model (for frozen graphs, it's explicitly specified).
https://github.com/uber/neuropod/blob/b18e281f3d29c91d2a43e4291abbe099ff2e852b/source/neuropod/backends/tensorflow/tf_backend.hh#L48-L49
https://github.com/uber/neuropod/blob/b18e281f3d29c91d2a43e4291abbe099ff2e852b/source/neuropod/backends/tensorflow/tf_backend.cc#L157-L170

2. In infer, we set up our `tensor_feeds` and `tensor_fetches`. These are the inputs/outputs we want to use with a TF callable. More details about callables in the code snippet: https://github.com/uber/neuropod/blob/b18e281f3d29c91d2a43e4291abbe099ff2e852b/source/neuropod/backends/tensorflow/tf_backend.cc#L320-L331

3. We populate `tensor_fetches` (the outputs we want). Note that this is the step that would fail without the check you referenced in the issue
https://github.com/uber/neuropod/blob/b18e281f3d29c91d2a43e4291abbe099ff2e852b/source/neuropod/backends/tensorflow/tf_backend.cc#L336-L350

4. We get a callable with the feeds and fetches we populated https://github.com/uber/neuropod/blob/b18e281f3d29c91d2a43e4291abbe099ff2e852b/source/neuropod/backends/tensorflow/tf_backend.cc#L373

One thing to note here is that a callable is a way of running a TF subgraph given a set of inputs and outputs. What I think you may be referring to is that it takes an _ordered_ list of feeds and an _ordered_ list of fetches and accepts/produces Tensors in the same order. This order is based on `tensor_feeds` and `tensor_fetches` (which have consistent orderings because they're `std::map`s).

5. We loop over the outputs (which are in the same order as `tensor_fetches`) and return the output https://github.com/uber/neuropod/blob/b18e281f3d29c91d2a43e4291abbe099ff2e852b/source/neuropod/backends/tensorflow/tf_backend.cc#L387-L396

So the "ordering" that it depends on is just an artifact of the way TF callables are run. It isn't based on anything outside of `infer`. We still need the names in the SavedModel output signature to match the names in the Neuropod output spec.

**Comment by VivekPanyam** [comment] 2022-06-03 01:03
Feel free to reopen I missed something, but I'll close this for now

**Closed by VivekPanyam** 2022-06-03 01:03 UTC
Labels: invalid
